amqp:
  admin:
    auto-create: false
  queues:
    insurance-quote-received:
      exchange: insurance-quote.events
      routing-key: insurance.quote.received
      queue: insurance.quote.received.queue
    insurance-policy-created:
      exchange: insurance-quote.events
      routing-key: insurance.policy.created
      queue: insurance.policy.created.queue

catalog_service:
  url: ${CATALOG_SERVICE_URL}

server:
  port: 8080
  undertow:
    threads:
      worker: 64
      io: 4

spring:
  application:
    name: insurance-quote-service
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.schema}
    password: ${postgres.password}
    username: ${postgres.username}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
      "[hibernate.check_nullability]": true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  rabbitmq:
    dynamic: ${amqp.admin.auto-create}
    host: ${amqp.host}
    port: ${amqp.port}
    username: ${amqp.username}
    password: ${amqp.password}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0